config/routes.rb
Lobsters::Application.routes.draw do
  scope :format => "html" do
    root :to => "home#index",
      :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
      :as => "root"

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user", :format => /html|json|rss/
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"

    get "/upvoted(.format)" => "home#upvoted"
    get "/upvoted/page/:page" => "home#upvoted"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"

    get "/signup" => "signup#index"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss|json/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"
    get "/search/:q" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
      get "suggest"
      post "suggest", :action => "submit_suggestions"
    end
    post "/stories/fetch_url_attributes", :format => "json"
    post "/stories/preview" => "stories#preview"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"
      end
    end
    get "/comments/page/:page" => "comments#index"
    get "/comments" => "comments#index", :format => /html|rss/

    get "/messages/sent" => "messages#sent"
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/s/:id/:title/comments/:comment_short_id" => "stories#show"
    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/c/:id" => "comments#redirect_from_short_id"
    get "/c/:id.json" => "comments#show_short_id", :format => "json"

    get "/u" => "users#tree"
    get "/u/:username" => "users#show", :as => "user", :format => /html|json/

    post "/users/:username/ban" => "users#ban", :as => "user_ban"
    post "/users/:username/unban" => "users#unban", :as => "user_unban"
    post "/users/:username/disable_invitation" => "users#disable_invitation", :as => "user_disable_invite"
    post "/users/:username/enable_invitation" => "users#enable_invitation", :as => "user_enable_invite"

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/pushover" => "settings#pushover"
    get "/settings/pushover_callback" => "settings#pushover_callback"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    get "/tags" => "tags#index"
    get "/tags.json" => "tags#index", :format => "json"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/hats" => "hats#index"
    get "/hats/build_request" => "hats#build_request",
      :as => "request_hat"
    post "/hats/create_request" => "hats#create_request",
      :as => "create_hat_request"
    get "/hats/requests" => "hats#requests_index"
    post "/hats/approve_request/:id" => "hats#approve_request",
      :as => "approve_hat_request"
    post "/hats/reject_request/:id" => "hats#reject_request",
      :as => "reject_hat_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"
    get "/chat" => "home#chat"

    if defined?(BbsController) || Rails.env.development?
      get "/bbs" => "bbs#index"
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :require_logged_in_user

  def index
    @title = t('.accountsettings')

    @edit_user = @user.dup
  end

  def delete_account
    if @user.try(:authenticate, params[:user][:password].to_s)
      @user.delete!
      reset_session
      flash[:success] = t('.deleteaccountflash')
      return redirect_to "/"
    end

    flash[:error] = t('.verifypasswordflash')
    return redirect_to settings_path
  end

  def pushover
    if !Pushover.SUBSCRIPTION_CODE
      flash[:error] = t('.pushovernotconfigured')
      return redirect_to "/settings"
    end

    session[:pushover_rand] = SecureRandom.hex

    return redirect_to Pushover.subscription_url({
      :success => "#{Rails.application.root_url}settings/pushover_callback?" <<
        "rand=#{session[:pushover_rand]}",
      :failure => "#{Rails.application.root_url}settings/",
    })
  end

  def pushover_callback
    if !session[:pushover_rand].to_s.present?
      flash[:error] = t('.pushovernorandomtokensession')
      return redirect_to "/settings"
    end

    if !params[:rand].to_s.present?
      flash[:error] = t('.pushovernorandomtokenurl')
      return redirect_to "/settings"
    end

    if params[:rand].to_s != session[:pushover_rand].to_s
      raise "rand param #{params[:rand].inspect} != " <<
        session[:pushover_rand].inspect
    end

    @user.pushover_user_key = params[:pushover_user_key].to_s
    @user.save!

    if @user.pushover_user_key.present?
      flash[:success] = t('.accountsetuppushover')
    else
      flash[:success] = t('.accountnolongersetuppushover')
    end

    return redirect_to "/settings"
  end

  def update
    @edit_user = @user.clone

    if @edit_user.update_attributes(user_params)
      flash.now[:success] = t('.updatesettingsflash')
      @user = @edit_user
    end

    render :action => "index"
  end

private

  def user_params
    params.require(:user).permit(
      :username, :email, :password, :password_confirmation, :about,
      :email_replies, :email_messages, :email_mentions,
      :pushover_replies, :pushover_messages, :pushover_mentions,
      :mailing_list_mode, :show_avatars, :show_story_previews,
      :show_submitted_story_threads
    )
  end
end

app/views/settings/index.html.erb
<div class="box wide">
  <div class="legend right">
    <a href="/u/<%= @user.username %>"><%= t('.viewprofile') %></a>
  </div>
  <div class="legend">
    <%= t('.accountsettings') %>
  </div>

  <%= form_for @edit_user, :url => settings_path, :method => :post,
  :html => { :id => "edit_user" } do |f| %>
    <%= error_messages_for f.object %>

    <div class="boxline">
      <%= f.label :username, t('.username'), :class => "required" %>
      <%= f.text_field :username, :size => 15 %>
      <span class="hint">
        <tt><%= User.username_regex %></tt>
      </span>
    </div>

    <div class="boxline">
      <%= f.label :password, t('.password'), :class => "required" %>
      <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :password_confirmation, t('.confirmpassword'),
        :class => "required" %>
      <%= f.password_field :password_confirmation, :size => 40,
        :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :email, t('.emailaddress'), :class => "required" %>
      <%= f.text_field :email, :size => 40 %>
      <span class="hint">
        <%= raw(t('.gravatarized')) %>
      </span>
    </div>

    <div class="boxline">
      <%= f.label :about, t('.about'), :class => "required" %>
      <%= f.text_area :about, :size => "100x5", :style => "width: 600px;" %>
    </div>

    <div class="box">
      <div class="boxline markdown_help_toggler" style="margin-left: 9em;
      width: 600px;">
        <div class="markdown_help_label">
          <%= t('.markdownformattingavailable') %>
        </div>

        <div style="clear: both;"></div>

        <%= render :partial => "global/markdownhelp" %>
      </div>
    </div>

    <p>
    <%= f.submit t('.saveaccountsettings') %>
    </p>

    <br>

    <div class="legend">
      <%= t('.notificationsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_user_key,
        raw(t(".pushover")),
        :class => "required" %>
      <%= link_to((f.object.pushover_user_key.present??
         t('.managepushoversubscription') : t('.subscribewithpushover')),
        "/settings/pushover", :class => "pushover_button", :method => :post) %>
      <span class="hint">
        <%= t('.foroptionalcomment') %>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.commentreplynotificationsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :email_replies, t('.receiveemail'), :class => "required" %>
      <%= f.check_box :email_replies %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_replies,  t('.receivepushover'),
        :class => "required" %>
      <%= f.check_box :pushover_replies %>
      <span class="hint">
        <%= t('.requirepushover') %>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.commentmentionnotificationsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :email_mentions, t('.receiveemail'), :class => "required" %>
      <%= f.check_box :email_mentions %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_mentions, t('.receivepushover'),
        :class => "required" %>
      <%= f.check_box :pushover_mentions %>
      <span class="hint">
        <%= t('.requirepushover') %>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.privatemessagenotificationsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :email_messages, t('.receiveemail'), :class => "required" %>
      <%= f.check_box :email_messages %>
    </div>

    <div class="boxline">
      <%= f.label :pushover_messages, t('.receivepushover'),
        :class => "required" %>
      <%= f.check_box :pushover_messages %>
      <span class="hint">
        <%= t('.requirepushover') %>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.submittedstorycommentsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :show_submitted_story_threads,
        raw(t('.showyourthreads')),
        :class => "required" %>
      <%= f.check_box :show_submitted_story_threads %>
    </div>

    <br>

    <div class="legend">
      <%= t('.mailinglistsettings') %>
    </div>

    <p>
    <%= raw(t('.mailinglisttext')) %>
    </p>

    <div class="boxline">
      <%= f.label :mailing_list_mode, t('.receivelistemails'),
        :class => "required" %>
      <%= f.select :mailing_list_mode, [ [ t('.listemailoption1'), 0 ],
        [ t('.listemailoption2'), 1 ], [ t('.listemailoption3'), 2 ] ] %>
    </div>

    <div class="boxline">
      <label class="required"><%= t('.listaddress') %></label>
      <span>
      <tt><%= Rails.application.shortname %>-<%=
        @edit_user.mailing_list_token %>@<%= Rails.application.domain %></tt>
      </span>
    </div>

    <br>

    <div class="legend">
      <%= t('.miscsettings') %>
    </div>

    <div class="boxline">
      <%= f.label :show_story_previews, t('.storypreview'),
        :class => "required" %>
      <%= f.check_box :show_story_previews %>
    </div>

    <div class="boxline">
      <%= f.label :show_avatars, t('.useravatars'), :class => "required" %>
      <%= f.check_box :show_avatars %>
    </div>


    <br>
    <%= f.submit t('.saveallsettings') %>
  <% end %>

  <br>
  <br>

  <a name="invite"></a>
  <div class="legend">
    <%= t('.inviteuser') %>
  </div>

  <% if @user.can_invite? %>
    <%= render :partial => "users/invitationform" %>
  <% else %>
      <%= t('.cannotsendinvitations') %>
  <% end %>

  <br>
  <br>

  <%= form_for @edit_user, :url => delete_account_path, :method => :post,
  :html => { :id => "delete_user" } do |f| %>
    <div class="legend">
      <%= t('.deleteaccount') %>
    </div>

    <p>
    <%= t('.deleteaccounttext') %>
    </p>

    <div class="boxline">
      <%= f.label :password,  t('.verifypassword'), :class => "required" %>
      <%= f.password_field :password, :size => 40, :autocomplete => "off" %>
    </div>

    <br>
    <%= f.submit t('.deleteaccountconfirmation') %>
  <% end %>
</div>