config/routes.rb
Lobsters::Application.routes.draw do
  scope :format => "html" do
    root :to => "home#index",
      :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
      :as => "root"

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user", :format => /html|json|rss/
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"

    get "/upvoted(.format)" => "home#upvoted"
    get "/upvoted/page/:page" => "home#upvoted"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"

    get "/signup" => "signup#index"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss|json/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"
    get "/search/:q" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
      get "suggest"
      post "suggest", :action => "submit_suggestions"
    end
    post "/stories/fetch_url_attributes", :format => "json"
    post "/stories/preview" => "stories#preview"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"
      end
    end
    get "/comments/page/:page" => "comments#index"
    get "/comments" => "comments#index", :format => /html|rss/

    get "/messages/sent" => "messages#sent"
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/s/:id/:title/comments/:comment_short_id" => "stories#show"
    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/c/:id" => "comments#redirect_from_short_id"
    get "/c/:id.json" => "comments#show_short_id", :format => "json"

    get "/u" => "users#tree"
    get "/u/:username" => "users#show", :as => "user", :format => /html|json/

    post "/users/:username/ban" => "users#ban", :as => "user_ban"
    post "/users/:username/unban" => "users#unban", :as => "user_unban"
    post "/users/:username/disable_invitation" => "users#disable_invitation", :as => "user_disable_invite"
    post "/users/:username/enable_invitation" => "users#enable_invitation", :as => "user_enable_invite"

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/pushover" => "settings#pushover"
    get "/settings/pushover_callback" => "settings#pushover_callback"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    get "/tags" => "tags#index"
    get "/tags.json" => "tags#index", :format => "json"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/hats" => "hats#index"
    get "/hats/build_request" => "hats#build_request",
      :as => "request_hat"
    post "/hats/create_request" => "hats#create_request",
      :as => "create_hat_request"
    get "/hats/requests" => "hats#requests_index"
    post "/hats/approve_request/:id" => "hats#approve_request",
      :as => "approve_hat_request"
    post "/hats/reject_request/:id" => "hats#reject_request",
      :as => "reject_hat_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"
    get "/chat" => "home#chat"

    if defined?(BbsController) || Rails.env.development?
      get "/bbs" => "bbs#index"
    end
  end
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user

  validate do
    unless email.to_s.match(/\A[^@ ]+@[^ @]+\.[^ @]+\z/)
      errors.add(:email, "is not valid")
    end
  end

  before_validation :create_code,
    :on => :create

  def create_code
    (1...10).each do |tries|
      if tries == 10
        raise "too many hash collisions"
      end

      self.code = Utils.random_str(15)
      unless Invitation.exists?(:code => self.code)
        break
      end
    end
  end

  def send_email
    InvitationMailer.invitation(self).deliver
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :require_logged_in_user,
    :except => [ :build, :create_by_request, :confirm_email ]

  def build
    if Rails.application.allow_invitation_requests?
      @invitation_request = InvitationRequest.new
    else
      flash[:error] = I18n.t 'controllers.invitations_controller.flashpublicinvitnotallowed'
      return redirect_to "/login"
    end
  end

  def index
    @invitation_requests = InvitationRequest.where(:is_verified => true)
  end

  def confirm_email
    if !(ir = InvitationRequest.where(:code => params[:code].to_s).first)
      flash[:error] = I18n.t 'controllers.invitations_controller.flashrequestconfirmation'
      return redirect_to "/invitations/request"
    end

    ir.is_verified = true
    ir.save!

    flash[:success] = I18n.t 'controllers.invitations_controller.flashsuccessinvitrequest'
    return redirect_to "/invitations/request"
  end

  def create
    if !@user.can_invite?
      flash[:error] = I18n.t 'controllers.invitations_controller.flashaccountnotinvit'
      redirect_to "/settings"
      return
    end

    i = Invitation.new
    i.user_id = @user.id
    i.email = params[:email]
    i.memo = params[:memo]

    begin
      i.save!
      i.send_email
      flash[:success] = I18n.t 'controllers.invitations_controller.flashsuccessinvit', :guest => "#{params[:email].to_s}"
    rescue
      flash[:error] = I18n.t 'controllers.invitations_controller.flasherrorssinvit'
    end

    if params[:return_home]
      return redirect_to "/"
    else
      return redirect_to "/settings"
    end
  end

  def create_by_request
    if Rails.application.allow_invitation_requests?
      @invitation_request = InvitationRequest.new(
        params.require(:invitation_request).permit(:name, :email, :memo))

      @invitation_request.ip_address = request.remote_ip

      if @invitation_request.save
        flash[:success] = I18n.t 'controllers.invitations_controller.flashrequestconfirmation', :email => "#{params[:invitation_request][:email].to_s}"
        return redirect_to "/invitations/request"
      else
        render :action => :build
      end
    else
      return redirect_to "/login"
    end
  end

  def send_for_request
    if !(ir = InvitationRequest.where(:code => params[:code].to_s).first)
      flash[:error] = I18n.t 'controllers.invitations_controller.flashinvalidinvitation'
      return redirect_to "/invitations"
    end

    i = Invitation.new
    i.user_id = @user.id
    i.email = ir.email

    i.save!
    i.send_email
    ir.destroy!
    flash[:success] = I18n.t 'controllers.invitations_controller.flashsuccessinvit', :guest => "#{ir.name.to_s}"
    return redirect_to "/invitations"
  end

  def delete_request
    if !@user.is_moderator?
      return redirect_to "/invitations"
    end

    if !(ir = InvitationRequest.where(:code => params[:code].to_s).first)
      flash[:error] = I18n.t 'controllers.invitations_controller.flashrequestconfirmation'
      return redirect_to "/invitations"
    end

    ir.destroy!
    flash[:success] = I18n.t 'controllers.invitations_controller.flashsuccessdeleteinvit', :name => "#{ir.name.to_s}"
    return redirect_to "/invitations"
  end
end

app/views/invitations/build.html.erb
<div class="box wide">
  <div class="legend">
  <%= t('.buildinvtitle') %>
  </div>

  <%= raw t('.buildinvtext') %>

  <%= form_for @invitation_request,
  :url => create_invitation_by_request_path do |f| %>
    <p>
    <%= f.label :name, t('.buildinvname') %>
    <%= f.text_field :name, :size => 30 %>
    <br />

    <%= f.label :email, t('.buildinvemail') %>
    <%= f.text_field :email, :size => 30 %>
    <br />

    <%= f.label :memo, t('.buildinvurl') %>
    <%= f.text_field :memo, :size => 30 %>
    <br />
    <label></label>
    <span class="na"><%= t('.buildinvverificationurl') %></span>
    </p>

    <p>
    <%= submit_tag t('.buildinvrequest') %>
    </p>
  <% end %>
</div>

app/views/invitations/index.html.erb
<div class="box wide">
  <div class="legend">
    <%= t('.requestedinvtitle') %>
  </div>

  <p>
  <%= t('.requestedinvsummary') %>
  </p>

  <table class="data" width="100%" cellspacing=0>
  <tr>
    <th width="15%"><%= t('.requestedinvdate') %></th>
    <th width="20%"><%= t('.requestedinvname') %></th>
    <th width="40%"><%= t('.requestedinvmemo') %></th>
    <th width="15%"></th>
    <% if @user.is_moderator? %>
      <th></th>
    <% end %>
  </tr>
  <% bit = 0 %>
  <% @invitation_requests.each do |ir| %>
    <tr class="row<%= bit %>">
      <td><%= ir.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
      <td><%= ir.name %>
        <% if @user.is_moderator? %>
          <br>
          <em><%= ir.email %></em>
        <% end %></td>
      <td><%= raw ir.markeddown_memo %></td>
      <td><%= form_tag send_invitation_for_request_path do %>
        <%= hidden_field_tag "code", ir.code %>
        <%= submit_tag t('.sendinvitation'), :data => { :confirm => "#{t('.confirminvitation')}" } %>
      <% end %></td>
      <% if @user.is_moderator? %>
        <td><%= form_tag delete_invitation_request_path do %>
          <%= hidden_field_tag "code", ir.code %>
          <%= submit_tag t('.deleteinvitation'), :data => { :confirm => "#{t('.confirmdelete')}" } %>
        <% end %></td>
      <% end %>
    </tr>
    <% bit = (bit == 1 ? 0 : 1) %>
  <% end %>
  <% if @invitation_requests.count == 0 %>
    <tr>
      <td colspan=<%= @user.is_moderator?? 5 : 4 %> align="center"><span
        class="na"><%= t('.noinvitation') %></span></td>
    </tr>
  <% end %>
  </table>
</div>